export const labels = {
  common: {
    create: 'Crear',
    edit: 'Editar',
    save: 'Guardar',
    cancel: 'Cancelar',
    loading: 'Cargando...',
    success: 'Operación exitosa',
    error: 'Ocurrió un error inesperado',
    search: 'Buscar...',
    noResults: 'Sin resultados',
    name: 'Nombre',
    delete: 'Eliminar',
    actions: 'Acciones',
    view: 'Ver',
    status: 'Estado',
    createdAt: 'Fecha de creación',
    active: 'Activo',
    inactive: 'Inactivo',
    blocked: 'Bloqueado',
    confirm: 'Confirmar',
    back: 'Volver',
    filters: 'Filtros',
    appName: 'Skeleton',
    selected: 'Seleccionado',
  },
  nav: {
    users: 'Usuarios',
    roles: 'Roles',
    dataScopes: 'Alcance de datos',
    security: 'Seguridad',
  },
  auth: {
    login: 'Iniciar sesión',
    logout: 'Cerrar sesión',
    email: 'Correo electrónico',
    password: 'Contraseña',
    rememberMe: 'Recordarme',
    forgotPassword: '¿Olvidaste tu contraseña?',
    resetPassword: 'Restablecer contraseña',
    sendResetLink: 'Enviar enlace de restablecimiento',
    newPassword: 'Nueva contraseña',
    confirmPassword: 'Confirmar contraseña',
    currentPassword: 'Contraseña actual',
    changePassword: 'Cambiar contraseña',
    resetSent: 'Se ha enviado el enlace de restablecimiento a tu correo.',
    resetSuccess: 'Tu contraseña ha sido restablecida.',
    loginFailed: 'Credenciales inválidas.',
    passwordChanged: 'Contraseña actualizada exitosamente.',
  },
  users: {
    title: 'Usuarios',
    create: 'Crear usuario',
    created: 'Usuario creado exitosamente.',
    updated: 'Usuario actualizado exitosamente.',
    empty: 'No hay usuarios registrados.',
    phone: 'Teléfono',
    lastLogin: 'Último acceso',
    avatar: 'Foto de perfil',
    roles: 'Roles',
    permissions: 'Permisos',
    forcePassword: 'Forzar cambio de contraseña',
    passwordForced: 'Contraseña del usuario actualizada.',
    avatarUploaded: 'Foto de perfil actualizada.',
    rolesUpdated: 'Roles del usuario actualizados.',
    fields: {
      name: 'Nombre',
      email: 'Correo electrónico',
      phone: 'Teléfono',
      status: 'Estado',
      password: 'Contraseña',
      passwordConfirmation: 'Confirmar contraseña',
    },
    statuses: {
      active: 'Activo',
      inactive: 'Inactivo',
      blocked: 'Bloqueado',
    },
    filters: {
      role: 'Filtrar por rol',
      status: 'Filtrar por estado',
      dateFrom: 'Desde',
      dateTo: 'Hasta',
    },
  },
  roles: {
    title: 'Roles',
    create: 'Crear rol',
    created: 'Rol creado exitosamente.',
    updated: 'Rol actualizado.',
    deleted: 'Rol eliminado.',
    duplicated: 'Rol duplicado exitosamente.',
    empty: 'No hay roles configurados.',
    duplicate: 'Duplicar',
    duplicateName: 'Nombre del nuevo rol',
    systemProtected: 'Rol de sistema (protegido)',
    permissionsSynced: 'Permisos actualizados.',
    fields: {
      name: 'Nombre',
      description: 'Descripción',
      usersCount: 'Usuarios',
      permissionsCount: 'Permisos',
    },
  },
  permissions: {
    title: 'Permisos',
    matrix: 'Matriz de permisos',
    effective: 'Acceso efectivo',
    source: {
      role: 'Heredado de rol',
      directGrant: 'Otorgado directamente',
      directDeny: 'Denegado explícitamente',
    },
    grant: 'Otorgar',
    deny: 'Denegar',
    none: 'Sin asignar',
    synced: 'Permisos directos actualizados.',
  },
  dataScopes: {
    title: 'Alcance de datos',
    create: 'Crear regla de alcance',
    created: 'Regla de alcance creada.',
    updated: 'Regla de alcance actualizada.',
    deleted: 'Regla de alcance eliminada.',
    empty: 'No hay reglas de alcance configuradas.',
    preview: 'Vista previa',
    previewResults: 'registros coinciden con esta regla',
    selectEntity: 'Seleccionar entidad',
    selectType: 'Seleccionar tipo de regla',
    rulesSynced: 'Reglas de alcance actualizadas.',
    fields: {
      name: 'Nombre',
      entity: 'Entidad',
      type: 'Tipo de regla',
      description: 'Descripción',
      configuration: 'Configuración',
    },
    types: {
      own: 'Solo registros propios',
      relation: 'Por relación',
      field_value: 'Por valor de campo',
      all: 'Acceso total',
      custom: 'Regla personalizada',
    },
    typeDescriptions: {
      own: 'El usuario solo ve los registros que creó.',
      relation: 'El usuario ve registros vinculados a él a través de otra entidad.',
      field_value: 'El usuario ve registros que cumplen una condición sobre un campo.',
      all: 'Sin restricción — el usuario ve todos los registros.',
      custom: 'Condición avanzada definida por código.',
    },
    configLabels: {
      ownerColumn: 'Columna del propietario',
      pivotTable: 'Tabla pivote',
      entityForeignKey: 'Clave foránea de la entidad',
      userForeignKey: 'Clave foránea del usuario',
      column: 'Columna',
      operator: 'Operador',
      value: 'Valor',
      scopeClass: 'Clase del scope',
    },
  },
} as const
